-- 코드를 입력하세요
# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, PRICE * SALES AS TOTAL_SALES FROM (SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01" GROUP BY BOOK_ID) AS BOOK_SALES
# NATURAL JOIN
# (SELECT * FROM AUTHOR NATURAL JOIN (SELECT AUTHOR_ID, BOOK_ID, CATEGORY, PRICE FROM BOOK) AS BOOK) AS T
# ORDER BY AUTHOR_ID, CATEGORY DESC;

-- SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01" GROUP BY BOOK_ID ORDER BY BOOK_ID
-- SELECT * FROM AUTHOR NATURAL JOIN (SELECT AUTHOR_ID, BOOK_ID, CATEGORY, PRICE FROM BOOK) AS BOOK;

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_PRICE) AS TOTAL_PRICE FROM (SELECT *, PRICE * SALES AS TOTAL_PRICE FROM (SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01" GROUP BY BOOK_ID) AS BOOK_SALES
NATURAL JOIN
(SELECT * FROM AUTHOR NATURAL JOIN (SELECT AUTHOR_ID, BOOK_ID, CATEGORY, PRICE FROM BOOK) AS BOOK) AS T) AS T2
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;