-- 코드를 입력하세요
WITH MILK AS (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk' GROUP BY CART_ID ORDER BY CART_ID),
YOGURT AS (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Yogurt' GROUP BY CART_ID)

SELECT CART_ID FROM MILK
JOIN YOGURT USING(CART_ID)
ORDER BY CART_ID;