-- 코드를 작성해주세요
# WITH SUWON AS (SELECT LOCATION1, LOCATION2, PM_VAL1, PM_VAL2, YEAR(YM) AS YEAR FROM AIR_POLLUTION WHERE LOCATION1 = '경기도' AND LOCATION2 = '수원')
# SELECT * FROM SUWON GROUP BY YEAR;
-- AVG(PM_VAL1) AS 'PM10', AVG(PM_VAL2) AS 'PM2.5'
SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS 'PM10', ROUND(AVG(PM_VAL2), 2) AS 'PM2.5' FROM AIR_POLLUTION WHERE LOCATION2 LIKE '%수원%'
GROUP BY YEAR
ORDER BY YEAR