-- 코드를 입력하세요
WITH WRITER_ID AS (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3)
SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8, 11)) AS 전화번호 FROM USED_GOODS_USER U INNER JOIN WRITER_ID W ON U.USER_ID = W.WRITER_ID
ORDER BY USER_ID DESC;
-- SELECT SUBSTRING('ASDF', 1, 2);
-- SELECT * FROM USED_GOODS_USER;