-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE FROM REST_INFO I NATURAL JOIN REST_REVIEW R WHERE ADDRESS LIKE "서울%" GROUP BY REST_ID ORDER BY SCORE DESC, FAVORITES DESC;
-- SELECT * FROM REST_INFO ORDER BY REST_ID;
-- SELECT * FROM REST_REVIEW ORDER BY REST_ID;