-- 코드를 입력하세요
-- SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT AS TOTAL_SALES FROM FOOD_PRODUCT P INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID WHERE DATE_FORMAT(O.PRODUCE_DATE, "%Y-%m") = "2022-05" ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE * AMOUNT AS TOTAL_SALES FROM FOOD_PRODUCT P NATURAL JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT FROM FOOD_ORDER WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05" GROUP BY PRODUCT_ID) AS O
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
