-- 코드를 입력하세요
# WITH APNT AS (SELECT APNT_NO, PT_NO, MCDP_CD, APNT_YMD, MDDR_ID FROM APPOINTMENT WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
# AND MCDP_CD = 'CD' AND APNT_CNCL_YN = 'N'),
# PT AS (
# SELECT APNT.APNT_NO, PT_NAME, APNT.PT_NO, APNT.MCDP_CD, APNT.APNT_YMD, APNT.MDDR_ID FROM PATIENT INNER JOIN APNT ON PATIENT.PT_NO = APNT.PT_NO),
# DT AS (
# SELECT PT.APNT_NO, PT.PT_NAME, PT.PT_NO, PT.MCDP_CD, DR_NAME, PT.APNT_YMD FROM DOCTOR INNER JOIN PT ON DOCTOR.DR_ID = PT.MDDR_ID)

# SELECT * FROM DT ORDER BY APNT_YMD;
WITH APNT AS (SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD FROM APPOINTMENT WHERE MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMd, "%Y-%m-%d") = '2022-04-13' AND APNT_CNCL_YN = 'N')
SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD FROM PATIENT P INNER JOIN (SELECT APNT_NO, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD FROM APNT A INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID) AS D ON P.PT_NO = D.PT_NO
ORDER BY APNT_YMD ASC;
-- SELECT * FROM APPOINTMENT