-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 FROM CTE
WHERE HOUR + 1 < 24),
OUTS AS (
    SELECT CAST(DATE_FORMAT(DATETIME, "%k") AS SIGNED) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS GROUP BY HOUR ORDER BY HOUR
)
SELECT C.HOUR, (
CASE 
    WHEN COUNT IS NULL THEN 0
    ELSE COUNT
END) AS COUNT FROM OUTS O RIGHT OUTER JOIN CTE C ON O.HOUR = C.HOUR;
# SELECT CAST(DATE_FORMAT(DATETIME, "%k") AS SIGNED) AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS O RIGHT OUTER JOIN CTE C;
# GROUP BY HOUR
# ORDER BY HOUR;