-- 코드를 작성해주세요
WITH FRONTEND AS (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE UPPER(CATEGORY) = 'FRONT END')
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS D INNER JOIN FRONTEND F ON D.SKILL_CODE & F.CODE > 0 ORDER BY ID;