-- 코드를 입력하세요
# SELECT (CASE
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-08" AND DATE_FORMAT(START_DATE, "%Y-%m") < "2022-09" THEN 8
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-09" AND DATE_FORMAT(START_DATE, "%Y-%m") < "2022-10" THEN 9
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-10" AND DATE_FORMAT(START_DATE, "%Y-%m") <= "2022-11" THEN 10
#     END) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID HAVING RECORDS >= 5
# ORDER BY CAR_ID DESC;

# SELECT CAR_ID, (CASE 
#        WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-08" AND DATE_FORMAT(END_DATE, "%Y-%m") < "2022-11" THEN "RENT" END) AS RENT, COUNT(*) AS COUNT
#        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#        GROUP BY CAR_ID
#        HAVING COUNT >= 5;

# SELECT (CASE
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-08" AND DATE_FORMAT(START_DATE, "%Y-%m") < "2022-09" THEN 8
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-09" AND DATE_FORMAT(START_DATE, "%Y-%m") < "2022-10" THEN 9
#     WHEN DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-10" AND DATE_FORMAT(START_DATE, "%Y-%m") <= "2022-11" THEN 10
#     END) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN
# (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, "%Y-%m") >= "2022-08" AND DATE_FORMAT(END_DATE, "%Y-%m") < "2022-11"
# GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5)
# GROUP BY CAR_ID
# ORDER BY MONTH, CAR_ID DESC;

# SELECT (CASE 
#        WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-08" THEN 8
#        WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-09" THEN 9
#        WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-10" THEN 10
#        END) AS MONTH, CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, "%Y-%m") IN ("2022-08", "2022-09", "2022-10")
# GROUP BY CAR_ID HAVING COUNT(*) >= 5
# ORDER BY CAR_ID;

SELECT (CASE 
       WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-08" THEN 8
       WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-09" THEN 9
       WHEN DATE_FORMAT(START_DATE, "%Y-%m") = "2022-10" THEN 10
       END) AS MONTH, CAR_ID, COUNT(*) AS RECOURDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10" AND
CAR_ID IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m") IN ("2022-08", "2022-09", "2022-10")
GROUP BY CAR_ID HAVING COUNT(*) >= 5)
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID DESC;