-- 코드를 입력하세요
-- SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS LIMIT 1;
SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH FROM USED_GOODS_FILE F RIGHT OUTER JOIN (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS B ON F.BOARD_ID = B.BOARD_ID ORDER BY FILE_ID DESC;
-- SELECT * FROM USED_GOODS_BOARD ORDER BY VIEWS DESC;
-- SELECT * FROM USED_GOODS_FILE;